import type { SiteConfig } from './config.types';

export const siteConfig: SiteConfig = {
  url: 'https://95gabor.me',
  title: 'Gábor Pichner | TypeScript Full-Stack Developer',
  description:
    'Experienced TypeScript Full-Stack Developer specializing in modern web technologies, cloud architecture, and DevOps. Expert in NestJS, Angular, and cloud platforms (AWS, Azure, GCP). Passionate about clean code, infrastructure as code, and building scalable applications.',
  keywords: [
    'Full-Stack',
    'Developer',
    'SRE',
    'DevOps',
    'Cloud',
    'Web-Application',
    'Microservice',
    'Microservices',
    'TypeScript',
    'JavaScript',
    'NodeJS',
    'NestJS',
    'REST API',
    'Angular',
    'React',
    'HTML',
    'CSS',
    'SCSS',
    'SQL',
    'NoSQL',
    'PostgreSQL',
    'MySQL',
    'MongoDB',
    'Docker',
    'Kubernetes',
    'Terraform',
    'AWS',
    'Azure',
    'GCP',
    'CI/CD',
    'DevOps',
    'Git',
    'JWT',
    'OAuth',
    'Clean Code',
    'Unit Testing',
    'Jest',
  ],
  favicon: 'icons/favicons/gabor-pichner.ico',
  cv: {
    filename: 'gabor-pichner', // ./content/<cv>.yaml without .yaml
  },
};
